_target_: src.models.module.BaseModule

criterion:
  _target_: torch.nn.BCELoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0

scheduler: null

net:
  _target_: libs.models.unet.u2net.u2net_S
  input_dim: 3
  output_dim: 1
  filters: [64, 64, 64, 64]
  n_blocks: [7, 6, 5, 4]
  init_type: null

# compile model for faster training with pytorch 2.0
compile: false
