_target_: src.models.module.BaseModule

criterion:
  _target_: libs.utils.losses.HybridLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1.0e-4

scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  _partial_: true
  lr_lambda:
    _target_: libs.utils.scheduler.lr_lambda2
    _partial_: true
    epochs: ${trainer.max_epochs}
    y1: 1
    y2: 5.0e-4

net:
  _target_: libs.models.unet.unet_ppp.UNet3Plus
  input_dim: 3
  output_dim: 1
  filters: [32, 64, 128, 256, 512]
  init_type: "kaiming"

# compile model for faster training with pytorch 2.0
compile: false
