defaults:
  - /model/net/transformer/vit/b16@_here_
  - /model/net/transformer/vit/pretrained/timm@_here_

config:
  shared_params:
    dropout: 0.1

  pretrained:
    path: ${paths.checkpoints_dir}/jx_vit_base_patch16_224_in21k-e5005f0a.pth

  patch_embedding:
    img_size: ${data.dataset.img_size}
    is_cls: false

  decoder:
    embedding_dim: ${model.net.config.shared_params.embedding_dim}
    decoder_dims: [256, 128, 64, 16]
