defaults:
  - /model/net/transformer/transunet/b16@_here_

config:
  pretrained:
    path: ${paths.checkpoints_dir}/jx_vit_base_resnet50_224_in21k-6f7c7740.pth

  patch_embedding:
    backbone_config:
      hybrid_backbone:
        _target_: libs.models.backbone.vit_resnet.ResNet
        _partial_: true
      grid_size: 16
      ratio: 1

  decoder:
    skip_dims: [512, 256, 64, 16]
    n_skips: 3
