config:
  shared_params:
    embedding_dim: 768

  pretrained: null

  patch_embedding:
    img_size: 224
    patch_size: 16
    embedding_dim: ${model.net.config.shared_params.embedding_dim}
    is_cls: true
    dropout: 0.1

  encoder:
    n_blocks: 12
    return_intermediate: false
    is_norm: true

  encoder_block:
    embedding_dim: ${model.net.config.shared_params.embedding_dim}
    n_heads: 12
    qkv_bias: false
    attn_dropout: 0.0
    proj_dropout: 0.1
    mlp_dim: 3072
    mlp_dropout: 0.1
