config:
  shared_params:
    embedding_dim: 768
    dropout: 0.0

  pretrained: null

  patch_embedding:
    img_size: 224
    patch_size: 16
    embedding_dim: ${model.net.config.shared_params.embedding_dim}
    backbone_config: null
    is_cls: true
    dropout: ${model.net.config.shared_params.dropout}

  encoder:
    n_blocks: 12
    return_intermediate: false
    is_norm: true

  encoder_block:
    embedding_dim: ${model.net.config.shared_params.embedding_dim}
    n_heads: 12
    qkv_bias: true
    attn_dropout: 0.0
    proj_dropout: ${model.net.config.shared_params.dropout}
    mlp_ratio: 4
    mlp_dropout: ${model.net.config.shared_params.dropout}
