defaults:
  - /model/net/transformer/vit/b16@_here_

config:
  hidden_size: 1024

  transformer:
    pretrained_path: ${paths.resources_dir}/checkpoints/ViT-L_16.npz
    mlp_dim: 4096
    n_heads: 16
    n_layers: 24
