defaults:
  - /model/net/transformer/vit/b16@_here_

config:
  patches:
    grid: [16, 16]

  transformer:
    pretrained_path: ${paths.resources_dir}/checkpoints/R50+ViT-B_16.npz

  resnet:
    num_layers: [3, 4, 9]
    width_factor: 1

  skip_channels: [512, 256, 64, 16]
