defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - curve_callback
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: true
  auto_insert_metric_name: false

early_stopping:
  monitor: "val/loss"
  patience: 5
  mode: "min"
  check_on_train_epoch_end: true

model_summary:
  max_depth: -1
