defaults:
  - /model/net/transformer/vit/b16@_here_

config:
  hidden_size: 384

  transformer:
    pretrained_path: ${paths.resources_dir}/checkpoints/ViT-S_16.npz
    mlp_dim: 1536
    n_heads: 6
    n_layers: 8

  resnet:
    type: resnet34
    pretrained_path: ${paths.resources_dir}/checkpoints/resnet34-333f7ec4.pth
    dims: [256, 128, 64]
