defaults:
  - /model/net/transformer/vit/b16@_here_

config:
  shared_params:
    embedding_dim: 512

  patch_embedding:
    img_size: ${data.dataset.img_size}
    dropout: null

  encoder:
    n_blocks: 4
    is_norm: false

  encoder_block:
    n_heads: 8
